# Generated by Django 4.1.7 on 2023-03-27 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.carrito'),
        ),
    ]
